### PR TITLE
Hello Microverse Project

### PR DESCRIPTION
**Pull request by malikali3**
this is first commit in which html file have been added with h1 tag stating title

### CODE REVIEW

**Review by ShoiraTa — CHANGES_REQUESTED** [review]
Hi @malikali3 ,

:thumbsup: This is good to make it this far, your project is really nice, congratulations on the good work you have done so far.

**First let me to point out:**

- Great commit history! ✔️ 
- You passed all the Linters! ✔️ 
- Professional pull request! ✔️ 

Keep on coding, good job so far! :clap:

There are some issues that you still need to work on to go to the next project but you are almost there!



 ## Required Changes  :recycle: 

- [x] Your .gitignore file is currently empty, however, based on project requirements, you should listin `test.md` file and `node_modules` directory. Please kindly add them. 

- [x] Please set up [a linter for HTML and CSS](https://github.com/microverseinc/linters-config) and make sure that all tests show green.
- [x] Please add descriptive README file to your project - please use [this template](https://github.com/microverseinc/readme-template) but remember to customize it to your project. 
- [x]  Pull Request should have a descriptive title telling you what changes are inside. But `this is first html commit` is not informative, please rename the pull request. You can it `Hello Microverse project`
- [x]  Pull Request should have a short summary describing introduced changes in more details. But in your case it is empty, please kindly add pull request description. 

- [x] OPTIONAL: Branch should have a name of a feature or action (e.g. 'created_sidebar' or 'added_comments_section'). In your case it is `secondbr` which is not informative enough. 
***
Cheers and Happy coding! :clap: :clap: :clap:

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. 

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

* * *
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Review by malikali3 — COMMENTED** [review]
first html file has been added in this commit

**Review by alexander16108 — CHANGES_REQUESTED** [review]
Hi @malikali3, 

Great work on making the changes 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


## Suggested changes
_Check the comments under the review._

-[ ] please you have linter errors, kindly fix them and resubmit for a review 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

**Comment by malikali3** [comment]
I need a one to one session because something is not working properly. Please arrange one

**Comment by malikali3** [comment]
Ok @alexander16108  @ShoiraTa 

thanks for sharing your valuable  advices I was really having difficulty using linters. I made changes again and again but nothing was working for me. Either there was an error in VS Code or Github actions but simply restarting my computer resolved all the issues. Now I have made all the changes you have asked for linters test is working for me. I will try to be more efficient next time.

Thank you

**Review by gemmen29 — APPROVED** [review]
Hi @malikali3, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



## Optional suggestions
- [Optional] Kindly change the README file name to `README.md` instead of `READ ME.txt`.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by malikali3** [comment]
@gemmen29 Thank you for your support just one thing do I need to re submit this project from student dashboard? or it will automatically be approved?

**Pull request merged**
